services:
  skillshare.api:
    image: skillshare.api
    build:
      context: .
      dockerfile: SkillShare.Api/Dockerfile

  skillshare.db:
    image: postgres
    container_name: skillsharedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SkillShare
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - "5050:80"

volumes:
  postgres_data:

networks:
  mynw:
